### PR TITLE
DEV-1205 : update elasticsearch package

### PR DESCRIPTION
**Pull request by wdgreene72**

### CODE REVIEW

**Comment by prashuj** [comment]
lgtm

**Comment by jib** [comment]
note that our production clusters currently install the 'latest' version of ES - let's make sure we don't inadvertently upgrade those before we merge.

cc @plathrop @dpricha89

**Comment by wdgreene72** [comment]
@jib is latest as defined by the master branch in this repos?

**Comment by jib** [comment]
latest as defined by what's in our apt repo, where the jenkins job generally puts packages once they're built

**Comment by prashuj** [comment]
FYI .. looks like jenkins builds the pkg from release branch

**Pull request merged**
